// Service Catalog
// Contains base provider rates and calculates selling prices with +Rs 50 markup.

const rawServices = [
    {
        "id": "13116",
        "category": "Instagram Reel Views ~ Cheapest In The World🚀",
        "name": "𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗥𝗲𝗲𝗹𝘀 𝗩𝗶𝗲𝘄𝘀 ~ 𝟱𝟬𝟬𝗞 𝗗𝗮𝘆 | 💨",
        "oldPrice": 0.16,
        "markup": 50.0,
        "min": 1000,
        "max": 10000000,
        "startTime": "12 minutes",
        "speed": "500K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13098",
        "category": "Instagram Reel Views ~ Cheapest In The World🚀",
        "name": "Instagram Reel Views 🫯🚀 ~ Update Special 🚨 | 𝐒𝐔𝐏𝐄𝐑 𝐅𝐀𝐒𝐓 𝐒𝐏𝐄𝐄𝐃 ⚡️",
        "oldPrice": 0.17,
        "markup": 50.0,
        "min": 500,
        "max": 3000000,
        "startTime": "04 minutes",
        "speed": "Super Fast",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13099",
        "category": "Instagram Reel Views ~ Cheapest In The World🚀",
        "name": "𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗥𝗲𝗲𝗹𝘀 𝗩𝗶𝗲𝘄𝘀 ⭐️ | 𝟱𝗠𝗶𝗹𝗹𝗶𝗼𝗻/𝗗𝗮𝘆🚀 | 𝗜𝗻𝘀𝘁𝗮𝗻𝘁 | 𝗖𝗲𝗹𝗲𝗯𝗿𝗶𝘁𝗶𝗲𝘀 𝗙𝗮𝘃𝗼𝘂𝗿𝗶𝘁𝗲 ❤️",
        "oldPrice": 0.2,
        "markup": 50.0,
        "min": 100,
        "max": 5000000,
        "startTime": "56 minutes",
        "speed": "5M/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11465",
        "category": "Instagram Reel Views ~ Cheapest In The World🚀",
        "name": "🚀 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗥𝗲𝗲𝗹 𝗩𝗶𝗲𝘄𝘀 💥 [𝟭𝟬𝗠𝗶𝗹𝗹𝗶𝗼𝗻/𝗗𝗮𝗶𝗹𝘆] [𝗦𝘂𝗽𝗲𝗿 𝗙𝗮𝘀𝘁 𝗦𝗽𝗲𝗲𝗱 ⚡]",
        "oldPrice": 0.26,
        "markup": 50.0,
        "min": 100,
        "max": 10000000,
        "startTime": "01 hours and 02 minutes",
        "speed": "10M/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11466",
        "category": "Instagram Reel Views ~ Cheapest In The World🚀",
        "name": "⭐ 𝗜𝗻𝘀𝘁𝗮𝗴𝗿𝗮𝗺 𝗥𝗲𝗲𝗹𝘀 𝗩𝗶𝗲𝘄𝘀 𝗙𝗼𝗿 𝗖𝗲𝗹𝗲𝗯𝗿𝗶𝘁𝗶𝗲𝘀 🚀 [ 𝐔𝐩𝐝𝐚𝐭𝐞 𝐢𝐧 𝐃𝐚𝐬𝐡𝐛𝐨𝐚𝐫𝐝⚡]",
        "oldPrice": 0.31,
        "markup": 50.0,
        "min": 100,
        "max": 2147483647,
        "startTime": "40 minutes",
        "speed": "Medium",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13113",
        "category": "Instagram Indian Likes 🇮🇳",
        "name": "Instagram Indian Like ❤️ ~ 🇮🇳 🚩🔱 ~ [ Premium Quality🔥 - Used By Creators 👀🗿🚀 ] - Recommended",
        "oldPrice": 50.02,
        "markup": 50.0,
        "min": 10,
        "max": 70000,
        "startTime": "01 hours and 18 minutes",
        "speed": "Medium",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11372",
        "category": "Instagram Indian Likes 🇮🇳",
        "name": "♚ Instagram Like [ 🇮🇳 𝐈𝐧𝐝𝐢𝐚𝐧 ] [🏆 Premium Quality - Non Drop - 30-50K+ Per Day - Instant ] - Recommended",
        "oldPrice": 55.45,
        "markup": 50.0,
        "min": 10,
        "max": 50000,
        "startTime": "Instant (02 hours and 51 minutes)",
        "speed": "30K-50K/day",
        "refill": "Non Drop",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13114",
        "category": "Instagram Indian Likes 🇮🇳",
        "name": "Instagram Real Active Indian Like 🇮🇳🛕🚩 ~ High Quality | Used By ♚ Influencer 📛👾",
        "oldPrice": 58.39,
        "markup": 50.0,
        "min": 50,
        "max": 100000,
        "startTime": "04 hours and 24 minutes",
        "speed": "Medium",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13127",
        "category": "Instagram Followers ~ Low Drop 🚩",
        "name": "Instagram Follower Real Account [ 0 to 3% drop ] Cancel enable | Instant Start | No Refill⚠️| 50k Day",
        "oldPrice": 421.92,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (10 hours and 25 minutes)",
        "speed": "50K/day",
        "refill": "Non Drop",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13100",
        "category": "Instagram Followers | Working After Update–",
        "name": "Instagram Followers 🥷🔥🚀 ~ App Data 💥 || Working After update ~ 30Days Refill ♻️",
        "oldPrice": 397.66,
        "markup": 50.0,
        "min": 50,
        "max": 1000000,
        "startTime": "19 hours and 13 minutes",
        "speed": "Medium",
        "refill": "30 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13101",
        "category": "Instagram Followers | Working After Update–",
        "name": "Instagram Followers 🥷🔥🚀 ~ App Data 💥 || Working After update ~ 365Days Refill ♻️",
        "oldPrice": 470.97,
        "markup": 50.0,
        "min": 50,
        "max": 1000000,
        "startTime": "43 hours and 29 minutes",
        "speed": "Medium",
        "refill": "365 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13096",
        "category": "Instagram Followers ~ ⭐️",
        "name": "Instagram Followers 🫯🔥❤️ ~ Mix Quality 👀 ~ 30Days Refill ♻️",
        "oldPrice": 425.23,
        "markup": 50.0,
        "min": 50,
        "max": 1000000,
        "startTime": "03 hours and 48 minutes",
        "speed": "Medium",
        "refill": "30 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13097",
        "category": "Instagram Followers ~ ⭐️",
        "name": "Instagram Followers 🫯🔥❤️ ~ Mix Quality 👀 ~ 90Days Refill ♻️",
        "oldPrice": 498.49,
        "markup": 50.0,
        "min": 50,
        "max": 1000000,
        "startTime": "31 hours and 28 minutes",
        "speed": "Medium",
        "refill": "90 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13102",
        "category": "Instagram Comment ~ Indian Mix🇮🇳",
        "name": "Instagram Random Comments 👻📛 [ Max 10K 🌟 ] ~ Indian 🇮🇳 Accounts Mix 🚩",
        "oldPrice": 87.16,
        "markup": 50.0,
        "min": 10,
        "max": 10000,
        "startTime": "02 hours and 44 minutes",
        "speed": "Medium",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "13103",
        "category": "Instagram Comment ~ Indian Mix🇮🇳",
        "name": "Instagram Custom Comments 👻📛 [ Max 10K 🌟 ] ~ Indian 🇮🇳 Accounts Mix 🚩",
        "oldPrice": 89.0,
        "markup": 50.0,
        "min": 10,
        "max": 10000,
        "startTime": "03 hours and 40 minutes",
        "speed": "Medium",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11373",
        "category": "Instagram Reel Views - New Server ⭐️",
        "name": "Instagram - Reels Views ( Cheapest In The World 🔥) ~ Max Unlimited ~ 300k/days ~ Instant ~ 𝐍𝐎 𝗥𝗘𝗙𝗜𝗟𝗟",
        "oldPrice": 0.1,
        "markup": 50.0,
        "min": 100,
        "max": 1000000,
        "startTime": "Instant (03 minutes)",
        "speed": "300K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11374",
        "category": "Instagram Reel Views - New Server ⭐️",
        "name": "Instagram Reels Views [ Max: Unlimited ] | All Link | Instant Start | Day 100k 🚀",
        "oldPrice": 0.15,
        "markup": 50.0,
        "min": 100,
        "max": 2147483647,
        "startTime": "Instant (03 minutes)",
        "speed": "100K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11375",
        "category": "Instagram Reel Views - New Server ⭐️",
        "name": "Instagram Reels Views [ Max: Unlimited ] | All Link | Instant Start | Day 500K 🚀",
        "oldPrice": 0.16,
        "markup": 50.0,
        "min": 500,
        "max": 3000000,
        "startTime": "Instant (05 minutes)",
        "speed": "500K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11376",
        "category": "Instagram Reel Views - New Server ⭐️",
        "name": "Instagram Reels Views [ Max: Unlimited ] | All Link | Instant Start | Day 1M 🚀",
        "oldPrice": 0.18,
        "markup": 50.0,
        "min": 100,
        "max": 5000000,
        "startTime": "Instant (09 minutes)",
        "speed": "1M/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11342",
        "category": "Instagram Post Views",
        "name": "Instagram Views For Photos From Explorer [ Max: Unlimited ] | Instant Start | Cancel Enable | No Refill ⚠️ | Speed: 200K/Day 🚀",
        "oldPrice": 1.5,
        "markup": 50.0,
        "min": 100,
        "max": 10000000,
        "startTime": "Instant (53 minutes)",
        "speed": "200K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11343",
        "category": "Instagram Post Views",
        "name": "Instagram Views For Photos [ Max: Unlimited ] | Instant Start | Cancel Enable | No Refill ⚠️ | Speed: 200K/Day 🚀",
        "oldPrice": 1.58,
        "markup": 50.0,
        "min": 10,
        "max": 100000000,
        "startTime": "Instant (09 minutes)",
        "speed": "200K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11363",
        "category": "Instagram Followers | Old Accounts + Posts 🔥",
        "name": "Instagram Followers | Old Accounts +Posts 📛 | No Refill ⚠️",
        "oldPrice": 253.95,
        "markup": 50.0,
        "min": 10,
        "max": 100000,
        "startTime": "30 hours and 57 minutes",
        "speed": "Medium",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11377",
        "category": "Instagram Indian Female Likes",
        "name": "Instagram Indian[💃 Female ] Likes [👌 Premium Quality + Profile Pic",
        "oldPrice": 67.15,
        "markup": 50.0,
        "min": 10,
        "max": 3000,
        "startTime": "02 hours and 04 minutes",
        "speed": "Medium",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11422",
        "category": "Instagram - Likes [ HQ Profiles - Best Prices ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ 1k/day ~ Instant ~ 𝐍𝐎 𝗥𝗘𝗙𝗜𝗟𝗟",
        "oldPrice": 7.08,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (18 hours and 41 minutes)",
        "speed": "1K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11423",
        "category": "Instagram - Likes [ HQ Profiles - Best Prices ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 50k ~ 50k/day ~ Instant ~ 𝐍𝐎 𝗥𝗘𝗙𝗜𝗟𝗟",
        "oldPrice": 7.08,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (27 hours and 21 minutes)",
        "speed": "50K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11424",
        "category": "Instagram - Likes [ HQ Profiles - Best Prices ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 100k/day ~ Instant ~ 𝐍𝐎 𝗥𝗘𝗙𝗜𝗟𝗟",
        "oldPrice": 7.68,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (08 hours and 12 minutes)",
        "speed": "100K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11425",
        "category": "Instagram - Likes [ HQ Profiles - Best Prices ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 100k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 30D",
        "oldPrice": 7.85,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (04 hours and 05 minutes)",
        "speed": "100K/day",
        "refill": "30 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11426",
        "category": "Instagram - Likes [ HQ Profiles - Best Prices ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 100k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 60D",
        "oldPrice": 8.01,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (14 hours and 26 minutes)",
        "speed": "100K/day",
        "refill": "60 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11427",
        "category": "Instagram - Likes [ HQ Profiles - Best Prices ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 100k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 90D",
        "oldPrice": 8.17,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (05 hours and 32 minutes)",
        "speed": "100K/day",
        "refill": "90 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11428",
        "category": "Instagram - Likes [ HQ Profiles - Best Prices ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 100k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 365D",
        "oldPrice": 8.35,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (17 hours and 06 minutes)",
        "speed": "100K/day",
        "refill": "365 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11429",
        "category": "Instagram - Likes [ HQ Profiles - Best Prices ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 100k/day ~ Instant ~ 𝐋𝐢𝐟𝐞𝐓𝐢𝐦𝐞",
        "oldPrice": 8.5,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (05 hours and 16 minutes)",
        "speed": "100K/day",
        "refill": "Lifetime",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11430",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 100k ~ 100k/day ~ Instant ~ 𝐍𝐎 𝗥𝗘𝗙𝗜𝗟𝗟",
        "oldPrice": 7.34,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (10 hours and 08 minutes)",
        "speed": "100K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11431",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 100k ~ 100k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 30D",
        "oldPrice": 7.5,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (07 hours and 29 minutes)",
        "speed": "100K/day",
        "refill": "30 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11432",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 100k ~ 100k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 60D",
        "oldPrice": 7.67,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (13 hours and 10 minutes)",
        "speed": "100K/day",
        "refill": "60 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11433",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 100k ~ 100k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 90D",
        "oldPrice": 7.83,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (Not Enough Data)",
        "speed": "100K/day",
        "refill": "90 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11434",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 100k ~ 100k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 365D",
        "oldPrice": 8.01,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (01 hours and 54 minutes)",
        "speed": "100K/day",
        "refill": "365 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11435",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 100k ~ 100k/day ~ Instant ~ 𝐋𝐢𝐟𝐞𝐓𝐢𝐦𝐞",
        "oldPrice": 8.15,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (05 hours and 08 minutes)",
        "speed": "100K/day",
        "refill": "Lifetime",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11436",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 200k/day ~ Instant ~ 𝐍𝐎 𝗥𝗘𝗙𝗜𝗟𝗟",
        "oldPrice": 13.79,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (Not Enough Data)",
        "speed": "200K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11437",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 200k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 30D",
        "oldPrice": 13.84,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (Not Enough Data)",
        "speed": "200K/day",
        "refill": "30 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11438",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 200k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 60D",
        "oldPrice": 14.0,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (Not Enough Data)",
        "speed": "200K/day",
        "refill": "60 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11439",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 200k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 90D",
        "oldPrice": 14.15,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (Not Enough Data)",
        "speed": "200K/day",
        "refill": "90 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11440",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 200k/day ~ Instant ~ 𝗥𝗘𝗙𝗜𝗟𝗟 365D",
        "oldPrice": 14.28,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (40 minutes)",
        "speed": "200K/day",
        "refill": "365 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11441",
        "category": "Instagram - Likes [ HQ Profiles - Cheapest ] ᴺᴱᵂ",
        "name": "Instagram Likes ~ 𝗛𝗤 𝗔𝗰𝗰𝗼𝘂𝗻𝘁 ~ Max 1M ~ 200k/day ~ Instant ~ 𝐋𝐢𝐟𝐞𝐓𝐢𝐦𝐞",
        "oldPrice": 14.46,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant (13 hours and 55 minutes)",
        "speed": "200K/day",
        "refill": "Lifetime",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11442",
        "category": "Instagram Likes [ Best Price – Provider ] ᴺᴱᵂ",
        "name": "Instagram Likes [ Max 1M ] | HQ Accounts | Cancel Enable | Non Drop | Instant Start | No Refill ⚠️ | Speed: 100K/Day 🚀",
        "oldPrice": 8.14,
        "markup": 50.0,
        "min": 10,
        "max": 5000000,
        "startTime": "Instant (02 hours and 28 minutes)",
        "speed": "100K/day",
        "refill": "Non Drop",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11443",
        "category": "Instagram Likes [ Best Price – Provider ] ᴺᴱᵂ",
        "name": "Instagram Likes [ Max 1M ] | HQ Accounts | Cancel Enable | Non Drop | Instant Start | 30 Days ♻️ | Speed: 100K/Day 🚀",
        "oldPrice": 8.3,
        "markup": 50.0,
        "min": 10,
        "max": 5000000,
        "startTime": "Instant (13 hours)",
        "speed": "100K/day",
        "refill": "30 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11444",
        "category": "Instagram Likes [ Best Price – Provider ] ᴺᴱᵂ",
        "name": "Instagram Likes [ Max 1M ] | HQ Accounts | Cancel Enable | Non Drop | Instant Start | 60 Days ♻️ | Speed: 100K/Day 🚀",
        "oldPrice": 8.47,
        "markup": 50.0,
        "min": 10,
        "max": 5000000,
        "startTime": "Instant (12 hours and 18 minutes)",
        "speed": "100K/day",
        "refill": "60 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11445",
        "category": "Instagram Likes [ Best Price – Provider ] ᴺᴱᵂ",
        "name": "Instagram Likes [ Max 1M ] | HQ Accounts | Cancel Enable | Non Drop | Instant Start | 90 Days ♻️ | Speed: 100K/Day 🚀",
        "oldPrice": 8.63,
        "markup": 50.0,
        "min": 10,
        "max": 5000000,
        "startTime": "Instant (20 hours and 41 minutes)",
        "speed": "100K/day",
        "refill": "90 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11446",
        "category": "Instagram Likes [ Best Price – Provider ] ᴺᴱᵂ",
        "name": "Instagram Likes [ Max 1M ] | HQ Accounts | Cancel Enable | Non Drop | Instant Start | 365 Days ♻️ | Speed: 100K/Day 🚀",
        "oldPrice": 8.79,
        "markup": 50.0,
        "min": 10,
        "max": 5000000,
        "startTime": "Instant (442 hours and 31 minutes)",
        "speed": "100K/day",
        "refill": "365 Days Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "11447",
        "category": "Instagram Likes [ Best Price – Provider ] ᴺᴱᵂ",
        "name": "Instagram Likes [ Max 1M ] | HQ Accounts | Cancel Enable | Non Drop | Instant Start | Lifetime ♻️ | Speed: 100K/Day 🚀",
        "oldPrice": 8.95,
        "markup": 50.0,
        "min": 10,
        "max": 5000000,
        "startTime": "Instant (16 hours and 51 minutes)",
        "speed": "100K/day",
        "refill": "Lifetime",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "4684",
        "category": "Instagram Followers",
        "name": "Instagram Followers [Refill 30 Days] [Speed 50K Day]",
        "oldPrice": 215.35,
        "markup": 50.0,
        "min": 10,
        "max": 1000000,
        "startTime": "Instant",
        "speed": "50K/day",
        "refill": "30 Days",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "4685",
        "category": "Instagram Likes",
        "name": "Instagram Likes [Real Active] [Speed 10K Day]",
        "oldPrice": 291.5,
        "markup": 50.0,
        "min": 50,
        "max": 500000,
        "startTime": "0-1 hr",
        "speed": "10K/day",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "4686",
        "category": "Instagram Views",
        "name": "Instagram Reels Views [Fast]",
        "oldPrice": 6.45,
        "markup": 50.0,
        "min": 100,
        "max": 5000000,
        "startTime": "Instant",
        "speed": "Fast",
        "refill": "Lifetime",
        "platform": "Instagram",
        "active": true
    },
    {
        "id": "4687",
        "category": "YouTube Views",
        "name": "YouTube Views [Non-Drop] [Monetization Safe]",
        "oldPrice": 335.69,
        "markup": 50.0,
        "min": 1000,
        "max": 10000000,
        "startTime": "0-12 hrs",
        "speed": "5K-10K/day",
        "refill": "Lifetime",
        "platform": "YouTube",
        "active": true
    },
    {
        "id": "4688",
        "category": "YouTube Subscribers",
        "name": "YouTube Subscribers [Real HQ] [Speed 100-300 Day]",
        "oldPrice": 403.0,
        "markup": 50.0,
        "min": 50,
        "max": 50000,
        "startTime": "0-24 hrs",
        "speed": "100-300/day",
        "refill": "30 Days",
        "platform": "YouTube",
        "active": true
    },
    {
        "id": "4689",
        "category": "Instagram Story",
        "name": "Instagram Story Views",
        "oldPrice": 0.12,
        "markup": 50.0,
        "min": 100,
        "max": 100000,
        "startTime": "Instant",
        "speed": "Fast",
        "refill": "No Refill",
        "platform": "Instagram",
        "active": true
    }
];

// Apply configured markup (default Rs 50 markup) to EVERY service price
const smmServices = rawServices.map(service => {
    const markup = (typeof service.markup === 'number') ? service.markup : (CONFIG.MARKUP !== undefined ? CONFIG.MARKUP : 50);
    return {
        ...service,
        price: parseFloat((service.oldPrice + markup).toFixed(2))
    };
});

// Utility to format price in INR
function formatCurrency(amount) {
    return new Intl.NumberFormat('en-IN', {
        style: 'currency',
        currency: 'INR'
    }).format(amount);
}

// Function to populate service dropdown on order page or display in services page
function getServiceById(id) {
    return smmServices.find(s => String(s.id) === String(id));
}

function getAllCategories() {
    const categories = new Set();
    smmServices.forEach(s => categories.add(s.category));
    return Array.from(categories);
}
